### ISSUE TITLE
consider providing standardized parameter files/`-P` for `sourmash sketch`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1910]
The goal would be to be able to encode collections of parameter strings in a file, to pass into `sourmash sketch` commands.

per Luiz [comment](https://github.com/sourmash-bio/sourmash/issues/1671#issuecomment-989501150), probably something in TOML:

>may I suggest [toml](https://toml.io/en/) instead of YAML? It would look something like this:
```toml
[[MinHashSpec.dna]]
ksize = [ 21, 31, 51 ]
scaled = 1_000

[[MinHashSpec.protein]]
input = [ "dna", "protein" ]
ksize = 10
scaled = [ 100, 200 ]

[[MinHashSpec.dayhoff]]
ksize = 16
```

>Many places (including Python with pyproject.toml) are moving away from YAML because it has some [confusing parsing issues](https://www.arp242.net/yaml-config.html#its-pretty-complex) (due to being underspecified).
